# Generated by Django 4.2.7 on 2023-12-10 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_issue_category_issue_date_created_issue_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Complaint',
        ),
    ]
