# Generated by Django 4.2.7 on 2023-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_issue_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(),
        ),
    ]
